version: "3"
services:
  sql:
    build: ./sql
    volumes:
      - web-say-cheeze:/var/lib/mysql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  app:
    build: ./app
    depends_on:
      - node
    ports:
      - 80:80
  node:
    build: ./apis
    env_file:
      - .env
    ports:
      - 8080:4200
    user: "node"
    volumes:
      - ./apis/utils:/home/node/app/utils
      - ./apis/src:/home/node/app/src
      - ./apis/tsconfig.json:/home/node/app/tsconfig.json
volumes:
  web-say-cheeze: